### ISSUE TITLE
QA Tests for Create main menu for maze

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#11] opened 2020-01-29 14:28 UTC
QA Testing for #1

**Comment by PohWanJun** [comment] 2020-01-31 14:36
have done test cases for this issue 
[Assignment Test Cases for Issue 1.docx](https://github.com/haraldtan/eti-maze-game/files/4139864/Assignment.Test.Cases.for.Issue.1.docx)

**Comment by haraldtan** [comment] 2020-02-03 05:52
Keep me updated on when you are able to finish the QA testing? @Eshwar72 
Thanks.

**Comment by Eshwar72** [comment] 2020-02-08 04:18
Committed the Automated Testing for this issue.
Best Regards
V Eshwar

**Comment by Eshwar72** [comment] 2020-02-08 18:30
[Assignment.Test.Cases.for.Issue.1.docx](https://github.com/haraldtan/eti-maze-game/files/4174903/Assignment.Test.Cases.for.Issue.1.docx)
Manual Testing for the Issue is done with updated Document

Best Regards,
V Eshwar

**Closed as completed** 2020-02-08 18:32 UTC
Labels: QA
